/**
 * Regenerate src/assets/images/README.md from src/data/image-specs.json.
 *
 * The spec file is the single source of truth; this turns it into the document
 * a person actually reads before preparing artwork. Run it after editing the
 * spec so the two can never disagree.
 *
 *   npm run images:readme
 */
import { readFileSync, writeFileSync, existsSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(fileURLToPath(new URL('../', import.meta.url)));
const IMAGES = join(root, 'src/assets/images');
const specs = JSON.parse(readFileSync(join(root, 'src/data/image-specs.json'), 'utf8'));

const kb = (file) => {
  const full = join(IMAGES, file);
  return existsSync(full) ? `${Math.round(statSync(full).size / 1024)}KB` : 'missing';
};

const placeholders = specs.images.filter((s) => s.status === 'placeholder');
const real = specs.images.filter((s) => s.status !== 'placeholder');
const upgradeable = real.filter((s) => s.replaceRecommended);

const lines = [
  '# Site images',
  '',
  'Generated by `npm run images:readme` from `src/data/image-specs.json`. Do not edit by hand.',
  '',
  '## How to replace any image',
  '',
  '1. Prepare your file at the dimensions listed below.',
  '2. Save it over the existing file in this folder, **keeping the exact same filename**.',
  '3. That is all. No code changes, no config, no imports to update.',
  '',
  'Every image is imported once in `src/data/images.ts` and referenced everywhere else',
  'by key, so a file swap needs no other edit. Alt text lives separately in',
  '`src/i18n/en/images.ts`, which means replacing a picture never disturbs its',
  'accessibility or SEO text.',
  '',
  'Astro compresses and re-encodes everything at build time and emits AVIF, WebP and',
  'JPEG at several widths. Supply the largest good-quality original you have and let',
  'the build do the optimising: do not pre-compress to the target file size.',
  '',
  '## Still needed',
  '',
  `**${placeholders.length} images are placeholders.** Each currently renders as a grey plate`,
  'printed with its own filename and target size, so nothing can ship looking like real',
  'content by mistake. During `npm run dev` they also carry an orange "Placeholder" badge.',
  '',
  '| # | Filename | Size (px) | Aspect | Format | Where it appears |',
  '| --- | --- | --- | --- | --- | --- |',
  ...placeholders.map((s, i) =>
    `| ${i + 1} | \`${s.file}\` | ${s.width} x ${s.height} | ${s.aspect ?? '-'} | ${s.format.toUpperCase()} | ${s.usedOn} |`,
  ),
  '',
  '### What each one should show',
  '',
  ...placeholders.flatMap((s) => [`**\`${s.file}\`**`, '', s.purpose, '']),
  '## Already in place',
  '',
  'Real assets carried over from the live site or supplied already.',
  '',
  '| Filename | Size (px) | On disk | Notes |',
  '| --- | --- | --- | --- |',
  ...real.map(
    (s) =>
      `| \`${s.file}\` | ${s.width} x ${s.height} | ${kb(s.file)} | ${s.replaceRecommended ? 'Usable, but a better version is worth supplying' : 'Good as is'} |`,
  ),
  '',
];

if (upgradeable.length) {
  lines.push(
    '### Worth upgrading when you can',
    '',
    ...upgradeable.flatMap((s) => [`**\`${s.file}\`**`, '', s.purpose, '']),
  );
}

lines.push(
  '## Client logos',
  '',
  'The ten logos in `clients/` are the organisations named on the live site. They are',
  'displayed in greyscale at rest and resolve to colour on hover, so a mixed set of',
  'brand palettes does not fight the page. Replace any of them the same way: same',
  'filename, any reasonable size, transparent background preferred.',
  '',
  '| Filename | Organisation | On disk |',
  '| --- | --- | --- |',
  ...specs.clients.map((c) => `| \`${c.file}\` | ${c.name} | ${kb(c.file)} |`),
  '',
  '## Guidance',
  '',
  '- Photography should look like Rwanda: Kigali and provincial roads, real depots and',
  '  yards, the vehicle types actually on the road here. Avoid stock photography that',
  '  could be anywhere, and avoid anything that reads as AI-generated.',
  '- Never fabricate a product interface. If a screenshot is needed, use the real app.',
  '- People in photographs should be shot respectfully and with permission.',
  '- Prefer JPEG for photographs and PNG only where transparency is genuinely needed.',
  '',
);

writeFileSync(join(IMAGES, 'README.md'), lines.join('\n'));
console.log(`Wrote src/assets/images/README.md (${placeholders.length} placeholders, ${real.length} real).`);
