/**
 * Kinyarwanda translation status.
 *
 * Walks the English dictionary, compares it against src/i18n/rw.ts, and reports
 * every string still waiting on a human translation. Writes the full list to
 * docs/translation-checklist.md so it can be handed to a translator as-is.
 *
 *   npm run i18n:status
 *
 * Nothing here fails the build: shipping with English fallback is the intended
 * launch state, not an error.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { build } from 'esbuild';

const root = resolve(fileURLToPath(new URL('../', import.meta.url)));

/** Bundle a TS entry to an in-memory ES module and import it. */
async function loadModule(entry, contents) {
  const result = await build({
    stdin: { contents, resolveDir: join(root, 'src/i18n'), sourcefile: entry, loader: 'ts' },
    bundle: true,
    write: false,
    format: 'esm',
    platform: 'neutral',
    logLevel: 'silent',
  });
  const code = result.outputFiles[0].text;
  return import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);
}

/* rw.ts imports types from ./index, which pulls in Astro-specific modules.
   Strip the type-only imports so the data can be loaded on its own. */
const rwSource = readFileSync(join(root, 'src/i18n/rw.ts'), 'utf8')
  .replace(/^import type .*$/gm, '')
  .replace(/:\s*DeepPartial<typeof en>/, '');

const enEntry = `
  export { common } from './en/common';
  export { home } from './en/home';
  export { products } from './en/products';
  export { services } from './en/services';
  export { companyPages } from './en/company';
  export { seo } from './en/seo';
  export { images } from './en/images';
`;

const en = await loadModule('en.ts', enEntry);
const { rw } = await loadModule('rw.ts', rwSource);

/** Every leaf string path in an object tree. Arrays count as a single leaf. */
function leaves(node, prefix = '') {
  if (typeof node === 'string') return [[prefix, node]];
  if (Array.isArray(node)) return node.every((v) => typeof v === 'string') ? [[prefix, node.join(' | ')]] : node.flatMap((v, i) => leaves(v, `${prefix}[${i}]`));
  if (node && typeof node === 'object') return Object.entries(node).flatMap(([k, v]) => leaves(v, prefix ? `${prefix}.${k}` : k));
  return [];
}

const enLeaves = leaves({
  common: en.common, home: en.home, products: en.products,
  services: en.services, companyPages: en.companyPages, seo: en.seo, images: en.images,
});
const rwPaths = new Set(leaves(rw).map(([path]) => path));

const pending = enLeaves.filter(([path]) => !rwPaths.has(path));
const done = enLeaves.length - pending.length;

/* Group by top-level namespace for a readable handoff. */
const groups = new Map();
for (const [path, value] of pending) {
  const group = path.split('.')[0];
  if (!groups.has(group)) groups.set(group, []);
  groups.get(group).push([path, value]);
}

const GROUP_TITLES = {
  common: 'Site chrome (navigation, footer, buttons, forms)',
  home: 'Homepage',
  products: 'Product pages',
  services: 'Service pages',
  companyPages: 'Company, legal and article pages',
  seo: 'Page titles and meta descriptions',
  images: 'Image alt text',
};

const lines = [
  '# Kinyarwanda translation checklist',
  '',
  `Generated by \`npm run i18n:status\`. Do not edit by hand.`,
  '',
  `**${done} of ${enLeaves.length} strings translated. ${pending.length} pending.**`,
  '',
  'Every pending string currently falls back to English on the live site, so',
  '`/rw/` pages are complete and readable; they are simply not yet in Kinyarwanda.',
  '',
  '## How to supply a translation',
  '',
  'Add the key path and its Kinyarwanda text to `src/i18n/rw.ts`, mirroring the',
  'structure of the English files. Anything added there wins over English at once;',
  'anything omitted keeps falling back. Re-run `npm run i18n:status` to update this list.',
  '',
  '## Already in the file, still needing native review',
  '',
  'The strings already present in `src/i18n/rw.ts` are interface chrome only, each',
  'marked `@review`. They were added so the language switcher could be tested end to',
  'end, and a native speaker should confirm every one of them before launch.',
  '',
  '## Pending strings',
  '',
];

for (const [group, entries] of groups) {
  lines.push(`### ${GROUP_TITLES[group] ?? group}  (${entries.length})`, '');
  lines.push('| Key | English |', '| --- | --- |');
  for (const [path, value] of entries) {
    const text = String(value).replace(/\|/g, '\\|').replace(/\n/g, ' ');
    lines.push(`| \`${path}\` | ${text.length > 180 ? `${text.slice(0, 180)}...` : text} |`);
  }
  lines.push('');
}

mkdirSync(join(root, 'docs'), { recursive: true });
writeFileSync(join(root, 'docs/translation-checklist.md'), lines.join('\n'));

console.log(`Kinyarwanda: ${done}/${enLeaves.length} translated, ${pending.length} pending.`);
for (const [group, entries] of groups) {
  console.log(`  ${String(entries.length).padStart(4)}  ${GROUP_TITLES[group] ?? group}`);
}
console.log('\nWritten: docs/translation-checklist.md');
